[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 25

[theme]
primaryColor = "#c084fc"
backgroundColor = "#0d091c"
secondaryBackgroundColor = "#181135"
textColor = "#ffffff"
font = "sans serif"
